name: Build and Test

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main

jobs:
  build_test:
    name: Build Test
    strategy:
      matrix:
        # os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        os: [ 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    # - name: Add MSBuild to PATH
    #   uses: microsoft/setup-msbuild@v1.0.0

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore

    - name: Build solution
      shell: pwsh
      run: |
        dotnet build -c Debug -v minimal

    - name: Test solution
      shell: pwsh
      run: |
        dir
        dotnet test -c Debug
